/*  <EzManager: Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

// Generated Jan 3, 2010 6:01:01 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.log.Log;


/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER", schema = "EZMANAGER")
public class Customer implements java.io.Serializable {

	@Logger private Log log;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2756996376460710508L;
	
	private long customerId;
	private String name;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Customer() {
	}

	public Customer(long customerId, String name) {
		this.customerId = customerId;
		this.name = name;
	}

	public Customer(long customerId, String name, Set<Project> projects,
			Set<Address> addresses, Set<Invoice> invoices) {
		this.customerId = customerId;
		this.name = name;
		this.projects = projects;
		this.addresses = addresses;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(generator = "seqCustomer")
	@SequenceGenerator(name="seqCustomer", sequenceName = "SEQ_CUSTOMER")
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PROJECT_CUSTOMER", schema = "EZMANAGER", joinColumns = { @JoinColumn(name = "CUSTOMER_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PROJECT_ID", nullable = false, updatable = false) })
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CUSTOMER_ADDRESS", schema = "EZMANAGER", joinColumns = { @JoinColumn(name = "CUSTOMER_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ADDRESS_ID", nullable = false, updatable = false) })
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
