/*  <EzManager: Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

//Generated Jan 3, 2010 6:01:01 PM by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceCustomerId generated by hbm2java
 */
@Embeddable
public class InvoiceCustomerId implements java.io.Serializable {

	private long invoiceId;
	private long customerId;

	public InvoiceCustomerId() {
	}

	public InvoiceCustomerId(long invoiceId, long customerId) {
		this.invoiceId = invoiceId;
		this.customerId = customerId;
	}

	@Column(name = "INVOICE_ID", nullable = false, precision = 10, scale = 0)
	public long getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(long invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false, precision = 10, scale = 0)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceCustomerId))
			return false;
		InvoiceCustomerId castOther = (InvoiceCustomerId) other;

		return (this.getInvoiceId() == castOther.getInvoiceId())
				&& (this.getCustomerId() == castOther.getCustomerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getInvoiceId();
		result = 37 * result + (int) this.getCustomerId();
		return result;
	}

}
