/*  <EzManager: Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

// Generated Jan 3, 2010 6:01:01 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.log.Log;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "TASK", schema = "EZMANAGER")
public class Task implements java.io.Serializable {

	@Logger private Log log;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5146727550246185528L;
	
	private long taskId;
	private Project project;
	private BaseStatus baseStatus;
	private String name;
	private long position;
	private Date startDate;
	private Date endDate;
	private Set<Cost> costs = new HashSet<Cost>(0);
	private Set<ExecutedTask> executedTasks = new HashSet<ExecutedTask>(0);

	public Task() {
	}

	public Task(long taskId, Project project, BaseStatus baseStatus,
			String name, long position, Date startDate, Date endDate) {
		this.taskId = taskId;
		this.project = project;
		this.baseStatus = baseStatus;
		this.name = name;
		this.position = position;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Task(long taskId, Project project, BaseStatus baseStatus,
			String name, long position, Date startDate, Date endDate, Set<Cost> costs, Set<ExecutedTask> executedTasks) {
		this.taskId = taskId;
		this.project = project;
		this.baseStatus = baseStatus;
		this.name = name;
		this.position = position;
		this.startDate = startDate;
		this.endDate = endDate;
		this.costs = costs;
		this.executedTasks = executedTasks;
	}

	@Id
	@GeneratedValue(generator = "seqTask")
	@SequenceGenerator(name="seqTask", sequenceName = "SEQ_TASK")
	@Column(name = "TASK_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	@NotNull
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ID", nullable = false)
	@NotNull
	public BaseStatus getBaseStatus() {
		return this.baseStatus;
	}

	public void setBaseStatus(BaseStatus baseStatus) {
		this.baseStatus = baseStatus;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "POSITION", nullable = false, precision = 10, scale = 0)
	public long getPosition() {
		return this.position;
	}

	public void setPosition(long position) {
		this.position = position;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<Cost> getCosts() {
		return this.costs;
	}

	public void setCosts(Set<Cost> costs) {
		this.costs = costs;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<ExecutedTask> getExecutedTasks() {
		return this.executedTasks;
	}

	public void setExecutedTasks(Set<ExecutedTask> executedTasks) {
		this.executedTasks = executedTasks;
	}

}
