/*  <Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

// Generated Jan 3, 2010 6:01:01 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.log.Log;


/**
 * BaseCurrency generated by hbm2java
 */
@Entity
@Table(name = "BASE_CURRENCY", schema = "EZMANAGER")
public class BaseCurrency implements java.io.Serializable {

	@Logger private Log log;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5204410788578436736L;
	private long currencyId;
	private String name;
	private Set<BaseVat> baseVats = new HashSet<BaseVat>(0);

	public BaseCurrency() {
	}

	public BaseCurrency(long currencyId, String name) {
		this.currencyId = currencyId;
		this.name = name;
	}

	public BaseCurrency(long currencyId, String name, Set<BaseVat> baseVats) {
		this.currencyId = currencyId;
		this.name = name;
		this.baseVats = baseVats;
	}

	@Id
	@GeneratedValue(generator = "seqBaseCurrency")
	@SequenceGenerator(name="seqBaseCurrency", sequenceName = "SEQ_BASE_CURRENCY")
	@Column(name = "CURRENCY_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(long currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baseCurrency")
	public Set<BaseVat> getBaseVats() {
		return this.baseVats;
	}

	public void setBaseVats(Set<BaseVat> baseVats) {
		this.baseVats = baseVats;
	}

}
