/*  <EzManager: Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

//Generated Jan 3, 2010 6:01:01 PM by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * InvoiceCustomer generated by hbm2java
 */
@Entity
@Table(name = "INVOICE_CUSTOMER")
public class InvoiceCustomer implements java.io.Serializable {

	private InvoiceCustomerId id;
	private Customer customer;
	private Invoice invoice;

	public InvoiceCustomer() {
	}

	public InvoiceCustomer(InvoiceCustomerId id, Customer customer,
			Invoice invoice) {
		this.id = id;
		this.customer = customer;
		this.invoice = invoice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "INVOICE_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", nullable = false, precision = 10, scale = 0))})
	@NotNull
	public InvoiceCustomerId getId() {
		return this.id;
	}

	public void setId(InvoiceCustomerId id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVOICE_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

}
