/*  <EzManager: Web application for activities follow up. As main features, you can create projects, then associate tasks and calculate their corresponding invoices. Each project is associated to one or more customers identified by their addressee>
    Copyright (C) <2010>  <Michel Petrovic> <email: dotnetmobile@gmail.com>

    Contributor(s): _____________________.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.dotnetmobile.ezmanager.entity;

// Generated Apr 15, 2010 7:01:47 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.log.Log;

/**
 * RoleIdentity generated by hbm2java
 */
@Entity
@Table(name = "ROLE_IDENTITY", schema = "EZMANAGER")
public class RoleIdentity implements java.io.Serializable {

	@Logger private Log log;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -3083519561026239800L;
	
	private long roleIdentityId;
	private String name;
	private Set<UserIdentity> userIdentities = new HashSet<UserIdentity>(0);

	public RoleIdentity() {
	}

	public RoleIdentity(long roleIdentityId, String name) {
		this.roleIdentityId = roleIdentityId;
		this.name = name;
	}

	public RoleIdentity(long roleIdentityId, String name,
			Set<UserIdentity> userIdentities) {
		this.roleIdentityId = roleIdentityId;
		this.name = name;
		this.userIdentities = userIdentities;
	}

	@Id
	@Column(name = "ROLE_IDENTITY_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getRoleIdentityId() {
		return this.roleIdentityId;
	}

	public void setRoleIdentityId(long roleIdentityId) {
		this.roleIdentityId = roleIdentityId;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USER_ROLE", schema = "EZMANAGER", joinColumns = { @JoinColumn(name = "ROLE_IDENTITY_ROLE_IDENTITY_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "USER_IDENTITY_USER_IDENTITY_ID", nullable = false, updatable = false) })
	public Set<UserIdentity> getUserIdentities() {
		return this.userIdentities;
	}

	public void setUserIdentities(Set<UserIdentity> userIdentities) {
		this.userIdentities = userIdentities;
	}

}
